/** Interfaz pública del módulo de asambleas (PRD §9.4, §9.5). */
export {
  conveneAssembly,
  issueCall,
  addAgendaItem,
  attachAgendaDocument,
  assemblyList,
  assemblyDetail,
  agendaItems,
  conveneAssemblySchema,
  issueCallSchema,
  addAgendaItemSchema,
  attachAgendaDocumentSchema,
  type ConveneAssemblyInput,
  type IssueCallInput,
  type AddAgendaItemInput,
  type AssemblyRow,
  type AssemblyDetail,
  type AgendaItemRow,
} from './application/assemblies';

export {
  freezeRoster,
  freezeElectionRoster,
  freezeConsultationRoster,
  rosterEntries,
  rosterPreview,
  frozenRoster,
  electionRoster,
  huellaDePadron,
  freezeRosterSchema,
  type FrozenRoster,
  type RosterPreview,
  type RosterView,
  type RosterEntryRow,
  type RosterEntryShape,
  type RosterCriteria,
} from './application/roster';

export {
  registerAttendance,
  computeQuorum,
  declareQuorum,
  attendanceList,
  pendingAttendees,
  registerAttendanceSchema,
  declareQuorumSchema,
  type RegisterAttendanceInput,
  type AttendanceResult,
  type AttendanceRow,
  type PendingAttendee,
  type QuorumComputation,
  type QuorumDeclaration,
} from './application/attendance';

export {
  recordResolution,
  publishMinutes,
  updateFollowUp,
  resolutionList,
  recordResolutionSchema,
  publishMinutesSchema,
  updateFollowUpSchema,
  type RecordResolutionInput,
  type RecordedResolution,
  type PublishMinutesInput,
  type UpdateFollowUpInput,
  type FollowUpEvidence,
  type ResolutionRow,
} from './application/resolutions';
